# Generated by Django 2.1.5 on 2019-01-16 20:06

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mail', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
                ('direction', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.PathAndRename('/img'))),
                ('tag', models.TextField(blank=True, null=True)),
                ('meting_date', models.TextField(blank=True, null=True)),
                ('meting_time_start', models.TextField(blank=True, null=True)),
                ('meting_time_end', models.TextField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
